language: scala
scala:
- 2.10.6
jdk:
- oraclejdk7
cache:
  directories:
  - "$HOME/.sbt"
  - "$HOME/.ivy2"
deploy:
  provider: script
  script: "./travis-deploy.sh"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
env:
  global:
  - secure: 5uI5Clq6wkG6nKRdNIekZUCffXpB1zlUs9Tm8c0ydDmSgtUOa/b0gO3RB1bYfjS20xFJpqjZ+l9fqdHf0E6r0nPHIrP6tAoxBE5w3GqX9SdEmS40fFk95e6/fAnMOswOuhjZ1SCpoTQEpLAqa0kHHqoDuwYIwXD1nrl/ihWZ8ceMWeTKDm7bjEyu79cnVaiOYBY0KrDutQsheUsNUV/WgYMe5w7DGcwAWDIUHTWjm9v6QjaQwZp/Bb5oR0FWcM4d7csvgGxnD6Z7TjpnGJ6DG3OiNn7aom/SuPreNDjjAncdElR6LHwOerCnp9qA3HTQRx8M2m70OT/TZ//kZw0YdHGfDPySyb9VXzOWDBqLviOH2qfWTmTN9Hx1YZ8jkBpDRICj6G9sHxbvWyBZDXV9JwARWkENlHHYa0LVV/A/3RVrhzDIX7/3a9IzrTiOczk2a4MhyBKT+SUFkqWMRLIU0ykeaq2TN4g927gZwJq1YX4AVFP7Cxhd8xyqkrY7Fv2AQtObUCiYCWkRzzGCOPCAxLX2tlbAJ+LuaQ2tEr1rxV4Lq/IMmf+gh7l1yn/oIV5JfhJP6qu/5W1DVP0Gh9amkwhgh0yCm0wq4wFkv49PFKcBWrpAsnnLXIzAtyZ3Xkmpjyj2/MGqcvOCgbt+OAoTpGCzyxQ4Ly4mBVUQ8otxokQ=
  - secure: GlFsVADXoXVfA26iYRRSOw4z4hz5y0XP8WeloBuP1p+5L6FYeYvxymc7QGuvZHd6UG5tKffcb2R7jttWvkDQX/FzCsGEh5gRH+uup/N3v2iltNHxZTku2iL7kv6/eLJ+9WwU1J1gUvwFWAr2SCqC0++yrG3S6e0AnhQH6LJ+qdREe/Qw+AAqBBYH7LFC256pL4+qO/v5ulspoR2c8BUMpUcla43o9G0UrZ73hpZNddRLNDIk+/iSkbewffrYnsOpSlXmi5qFC3MBOYd9NGWR7KHrE9BrF6JOuN7agG6iDWThVjWWLk416zh1869rD32eT2gGqa5zdzgSpqaDNf+hTMTD06OXRzTN36XyKNy7dtT4QxSdEKpYYWPasDfJWaLSgENLzxquLThISWhsqFDAbH19tn7atBOAhGDH46u7ubY8lgqhngyDsHKfWpEzNZkrsuMCbGtGMAVJzbqggNNRoQGClW5m3y5xmRuAmBk7C/rGS0QuTzC3vTlDc8Ne3PZMq+9w2wOVhqQTYjcfs4CnkhaGVcJRWJdfYue5sgyze31E0ocGbn2ER7cNtm9A5gMQKEYRKH7zuFV82l59+1lGBNVqzZekThqc6WAqWYBjAVlcAXoD1oABg5i5NekXNecD1p75p6spPm4Zedh8Xg/9QIMrV9RtPB6E2L2pbN1v634=
